version: '3.8'

services:
  unicompass-backend:
    build: .
    container_name: unicompass
    restart: unless-stopped
    ports:
      - "80:5000"
    environment:
      - DEBUG=false
      - PORT=5000
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s