apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  labels:
    app: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - name: orchestrator
        image: unicompass/orchestrator:latest
        ports:
        - containerPort: 5000
        env:
        - name: RESUME_AGENT_URL
          value: http://resume-agent-service:5001
        - name: PREDICTION_AGENT_URL
          value: http://prediction-agent-service:5002
        - name: SOP_AGENT_URL
          value: http://sop-agent-service:5003
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
spec:
  selector:
    app: orchestrator
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer