apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-agent
  labels:
    app: resume-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-agent
  template:
    metadata:
      labels:
        app: resume-agent
    spec:
      containers:
      - name: resume-agent
        image: unicompass/resume-agent:latest
        ports:
        - containerPort: 5001
        env:
        - name: FLASK_ENV
          value: production
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PORT
          value: "5001"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: resume-agent-service
spec:
  selector:
    app: resume-agent
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: LoadBalancer