version: '3.9'
services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: sop_agent
      POSTGRES_USER: sopuser
      POSTGRES_PASSWORD: soppass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sopuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
      - .:/app

  sop_agent:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: postgresql://sopuser:soppass@db:5432/sop_agent
    ports:
      - "5003:5003"
    volumes:
      - .:/app
    command: python main.py

volumes:
  pgdata:
