version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      SECRET_KEY: supersecret
      DATABASE_URL: postgresql://sop_user:sop_password@postgres:5432/sop_agent
      FLASK_ENV: development
    ports:
      - "5003:5003"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped
    command: ["python", "main.py"]
    stdin_open: true
    tty: true